  
test_configuration_common:
  normalize: True
  image_size: 256
  metric: clipseg_eval.metrics.FixedIntervalMetricsWithMatching
  batch_size: 1
  test_dataset: waffle
  sigmoid: False
  # max_iterations: 250
  custom_threshold: 0.25

  dataset_root: data/waffle_benchmark_processed/
  semantic_classes: 3
  dataset_name: waffle
  image_norm: False
  poly2seq: False
  num_bins: 32
  seq_len: 512
  add_cls_token: False
  per_token_class: True
  input_channels: 3
  mask_format: bitmask
  pred_json_root: 

test_configuration: 
  name: coco
  mask: text

columns: [name,
pas_t_fgiou_best, pas_t_miou_best,  pas_t_fgiou_ct,
pas_h_fgiou_best, pas_h_miou_best,  pas_h_fgiou_ct,
pas_h2_fgiou_best, pas_h2_miou_best,  pas_h2_fgiou_ct, pas_h2_fgiou_best_t,
train_loss, duration, date
]

individual_configurations:

- {name: roomformer, remove_classes: [pas5i, 0], negative_prob: 0.0, test_configuration: {splits: [0], custom_threshold: 0.25}}
- {name: autoroom, remove_classes: [pas5i, 1], negative_prob: 0.0, test_configuration: {splits: [0], custom_threshold: 0.25}}

# baseline